name: 'Test on Windows'

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test-on-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install Browsers
        run: |
          choco install -y opera opera-gx brave chromium vivaldi librewolf --no-progress

          # chrome, edge, and firefox are already installed
          # See: https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md

      - name: Install Python Dependencies
        run: |
          pip install -r tests/test-requirements.txt
      - name: Run Browser Tests
        run: |
          python -m unittest -v
